PT-640 Display of parameter history is not accurate
mdblp/viz pull request #29
Opened 2019-09-13 16:22 UTC by yvon-dblg

Hot fix.

2019-09-14 04:35 UTC, franck-fourel requested changes
little change for sorting

2019-09-14 04:35 UTC, franck-fourel commented on src/components/settings/DiabeloopHistoryParameters.js
> +          parameters.sort((a, b) => b.name.localeCompare(a.name));
As we have now different levels of parameters, I just realized we should sort on 2 fields: level and name. Can you apply the below change:
```suggestion
          parameters.sort((a, b) =>  
            b.level.toString().localeCompare(a.level.toString())
            || b.name.localeCompare(a.name)
            );
```

2019-09-15 18:32 UTC, franck-fourel approved these changes

2019-09-15 18:36 UTC, franck-fourel commented
@yvon-dblg can you please review the change I did on the sorting in 4deb40706a83afd6063634a2969ebdfc9f290a37

2019-09-16 07:48 UTC, yvon-dblg reviewed
OK LGTM

2019-09-16 08:50 UTC, merged

2019-09-16 09:07 UTC, ydrisR approved these changes
LGTM