PT-1304 Display inputTime property when available
mdblp/viz pull request #68
Opened 2020-07-31 16:02 UTC by franck-fourel

2020-08-05 07:47 UTC, yvon-dblg requested changes
It works 👍 
There is a few minor things to update.

In `src/components/daily/physicaltooltip/PhysicalTooltip.js`: Missing normalTime in propTypes for physicalActivity
```
  physicalActivity: PropTypes.shape({
    normalTime: PropTypes.string.isRequired,
    reportedIntensity: PropTypes.string.isRequired,
    duration: PropTypes.shape({
      units: PropTypes.string.isRequired,
      value: PropTypes.number.isRequired,
    }).isRequired,
  }).isRequired,
```

I think the tooltip is not well balanced.
![image](https://user-images.githubusercontent.com/53182545/89385844-88019b80-d700-11ea-8459-bc67e45d790e.png)
@MarineDBL any advice ?

2020-08-05 07:47 UTC, yvon-dblg commented on src/components/daily/bolustooltip/BolusTooltip.js
> +        <div className={styles.label}>{t('Entered at {{date}}', {date: formatInputTime(bolus.inputTime, timePrefs)})}</div>
`'bolus.inputTime' is missing in props validationeslintreact/prop-types`
Add line 437: `inputTime: PropTypes.string,`
```
  bolus: PropTypes.shape({
    type: PropTypes.string.isRequired,
    inputTime: PropTypes.string,
  }).isRequired,
```

2020-08-05 07:47 UTC, yvon-dblg commented on src/components/daily/physicaltooltip/PhysicalTooltip.js
> +  return <div className={styles.container}>{rows}{inputTime}</div>;
```suggestion
    return <div className={styles.container}>{rows}{inputTime}</div>;
```

2020-08-05 07:47 UTC, yvon-dblg commented on src/components/daily/physicaltooltip/PhysicalTooltip.js
> +      )
```suggestion
      );
```

2020-08-05 07:47 UTC, yvon-dblg commented on src/components/daily/physicaltooltip/PhysicalTooltip.js
> +        </div>
```suggestion
        </div>
```

2020-08-05 07:47 UTC, yvon-dblg commented on src/utils/format.js
> + * @return {String} percentage
```suggestion
 * Format Input Time
 * @param {string|number|Date|moment.Moment} utcTime Zulu timestamp (Integer hammertime also OK)
 * @param {{timezoneAware: boolean, timezoneName?: string}} timePrefs
 *
 * @return {string} The formated time for input time in the terminal
```

2020-08-06 08:54 UTC, franck-fourel commented
@MarineDBL do you want to request any changes in this PR or should we accept it as it is ?

2020-08-06 09:03 UTC, MarineDBL commented
@franck-fourel I gave feedback to @yvon-dblg 
Wording is ok but text should be aligned left for the titles and right for the rest - including the hour.

2020-08-10 13:43 UTC, yvon-dblg requested changes
One thing left

2020-08-10 13:43 UTC, yvon-dblg commented on src/components/daily/physicaltooltip/PhysicalTooltip.js
> +            {t('{{date}}', {date: formatInputTime(pa.inputTime, timePrefs)})}
We will have a translation string `{{date}}` with nothing to be translated.
```suggestion
            {formatInputTime(pa.inputTime, timePrefs)}
```

2020-08-10 15:43 UTC, yvon-dblg approved these changes
LGTM

2020-08-10 15:43 UTC, merged