[YLP-109] block weight depending on country
mdblp/viz pull request #73
Opened 2020-11-05 09:01 UTC by Nas84

2020-11-06 10:36 UTC, yvon-dblg requested changes
- Changelog: Too many line changed

2020-11-06 15:17 UTC, yvon-dblg requested changes
It's working.
Need few changes I think, specially of the 'units' -> 'unit' case.

2020-11-06 15:17 UTC, yvon-dblg commented on src/utils/data.js
> +
```suggestion

```

2020-11-06 15:17 UTC, yvon-dblg commented on src/components/common/stat/Stat.js
> +    }
```suggestion
    }
```

2020-11-06 15:17 UTC, yvon-dblg commented on src/utils/data.js
> +  };
```suggestion
  /**
   * Retreive the patient weight from the pump settings
   * @returns {{ name: 'WEIGHT', value: string, unit: string, level: number }}
   */
  getWeight() {
    // retrieve lastest pump settings
    const pumpSettings = _.last(this.filter.byType('pumpSettings').top(Infinity));
    const parameters = _.get(pumpSettings, 'payload.parameters');
    const weight = _.find(parameters, { name: 'WEIGHT' });

    if (_.isEmpty(weight)) {
      return null;
    }

    return weight;
  }
```
Better to return `null` instead of `undefined`, because `typeof null === "object"`.
`undefined` is a Javascript aberration.
I generally prefer, when possible to use the 'positive' test, instead of the negative one.

2020-11-06 15:17 UTC, yvon-dblg commented on src/utils/stat.js
> +            suffix: data.weight ? (data.weight.units ? (data.weight.units) : 'kg' ) : 'kg',
Simplify by:
```suggestion
            suffix: _.get(data, 'weight.unit', 'kg'),
```
Note: Typo in portal-api for the units: it's `unit`.

2020-11-06 15:17 UTC, yvon-dblg commented on src/utils/stat.js
> +            value: data.weight ? (data.weight.value ? ensureNumeric(data.weight.value) : undefined ) : undefined,
```suggestion
            value: ensureNumeric(_.get(data, 'weight.value')),
```

2020-11-06 15:17 UTC, yvon-dblg commented on test/utils/data.test.js
> +        weight: undefined
```suggestion
    it('should return null weight when no pump settings found', () => {
      const du = new DataUtil(data, defaultOpts);
      du.endpoints = dayEndpoints;
      expect(du.getTotalInsulinAndWeightData()).to.eql({
        totalInsulin: 16.5,
        weight: null,
      });
```
To fix the test if previous suggestions are applied.

2020-11-06 15:17 UTC, yvon-dblg commented on test/utils/stat.test.js
> +          units: 'kg'
```suggestion
          unit: 'kg'
```

2020-11-06 15:17 UTC, yvon-dblg commented on test/utils/stat.test.js
> +          units: 'kg'
```suggestion
          unit: 'kg'
```

2020-11-06 15:17 UTC, yvon-dblg commented on test/utils/stat.test.js
> +          units: 'kg'
```suggestion
          value: 154,
          unit: 'lb'
```
Better to test another units too, if to test if the default value is working.

2020-11-06 15:17 UTC, yvon-dblg commented on test/utils/stat.test.js
> +            suffix: 'kg',
```suggestion
            suffix: 'lb',
```

2020-11-06 15:17 UTC, yvon-dblg commented on test/utils/stat.test.js
> +            value: 70,
```suggestion
            value: 154,
```

2020-11-06 15:32 UTC, yvon-dblg commented
Can you also bump lodash ?
```
"lodash": "^4.17.20",
```

2020-11-09 09:26 UTC, Nas84 commented
just for info, the "units" word it was coming from the data test files used in the systems tests

2020-11-09 16:11 UTC, yvon-dblg approved these changes
LGTM

2020-11-09 16:11 UTC, merged